Banner
codeandcoffeestl/website pull request #3
Opened 2024-03-11 03:45 UTC by itsHackinTime

I had some trouble styling buttons on the hero page. all of my styles would be overruled by the button styling from Prime React. I am also in need of an updated / better-resolution picture, and I am unsure about the font on the page. otherwise, the component is completed

2024-03-12 22:03 UTC, tudor-seserman commented on client/src/components/home/HeroC.tsx
> +                    className="p-hero-buttons text-xl mr-3 bg-YHighlightColor text-PrimaryColor "
I think the buttons should be OHighlightColor. The orangy highlight color,

2024-03-12 22:06 UTC, tudor-seserman requested changes
Looks good to me. Just the buttons should be OHighlightColor to match the Design. Also the font in the design is RocknRoll One, but it looks different on the page.

2024-03-14 01:24 UTC, itsHackinTime commented
I didn't see a file for a "RocknRoll One" font, so I added a .ttf file to assets>custom-theme>tailwind-custom>fonts and added the @fontface in tailwind-custom>_fonts. after I made that change, most fonts were transformed to "RocknRoll One". I changed the order of ::root > font-family so "RocknRoll One" is at the back of the list. Other than that I changed the color of the buttons to OHighlightColor.

2024-03-14 01:34 UTC, tudor-seserman approved these changes

2024-03-14 01:35 UTC, merged